// <auto-generated />
namespace bsk2v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Recipecontrollerimplementation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Recipecontrollerimplementation));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201445325_Recipe controller implementation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
